### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by dk2909** [dk2909/COSC-4351#16]
- implement get request for address verification API
- Anvil has tutorials to write own API's, maybe that can be used to paste in the code USPS,FedEx, etc. would give us
- can be created and tested on a separated Anvil Project and tied in later

**Comment by dk2909** [comment]
Just came across an example get request:

![image](https://user-images.githubusercontent.com/48042692/79801765-55d05780-8324-11ea-8dfe-5cc0aee12380.png)

**Comment by aqnguye4** [comment]
Hey Daniel,

[Testing API.txt](https://github.com/dk2909/COSC-4351/files/4530395/Testing.API.txt)

I tailor the code into the Anvil previous code already but when I try to run it on the Anvil webpage, it was just stalling. So there is an error.
So I figure out that Anvil doesnt have the package install yet.

And that is what I am stuck at.

So i follow your advice, but didnt get far.

**Comment by dk2909** [comment]
API is working now, https get request through cloud.
