### ISSUE TITLE
Implement User Checkouts

### ISSUE THREAD

**Issue by dk2909** [dk2909/COSC-4351#17]
- tie check out items to user data table -->DONE
- implement login and taking over items-->DONE
- clear items later after checkout-->DONE
- add total checkout-->DONE
- update shipping front end page-->DONE

**Comment by baspivey** [comment]
Review and give feedback
testing username and password
test@test.com
1234

**Comment by dk2909** [comment]
Looks good to me. Only one non-functional thing I've realized so far: At checkout, the order total has a lot of decimals.
I will bring up whatever comes up during the unit test development.

**Comment by baspivey** [comment]
Fixed decimal to show only 2 places
